### ISSUE TITLE
Problem with running server.js on Linux Mint

### ISSUE THREAD

**Issue by kchau101** [swiftceipt/SC-XW1#12]
Issue with running the application on my system.
```
kevin@kevin-CM1831 ~/git/SC-XW1 $ nodejs server.js 

module.js:340
    throw err;
          ^
Error: Cannot find module 'Chance'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/kevin/git/SC-XW1/server.js:6:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

Can you reproduce on your machines? I fixed by changing **server.js:6**

`var Chance = require('chance');`

**Comment by SivanMehta** [comment]
I cannot reproduce this on my machine, as the server seems to start even with the line being unchanged. I have posted the full command line log [here](https://gist.github.com/SivanMehta/a0d274ac3fdad35c284a).

Weirdly, it works with **both** your changes and the original. Maybe @ziyunzamy or @eterui can check on their machines.

**Comment by SivanMehta** [comment]
@kchau101 expressed in our meeting today that this was resolved.
